import Config

# Enable dev routes in production for component showcase
config :elixir_lizards, dev_routes: true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :elixir_lizards, ElixirLizardsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures force_ssl for redirecting HTTP to HTTPS.
# The health check path is excluded so Fly.io's internal HTTP health checks work.
# Note `:force_ssl` is required to be set at compile-time.
config :elixir_lizards, ElixirLizardsWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [paths: ["/health"]]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
